project:
  type: website

website:
  title: "BIOL2022"
  navbar:
    left:
      - icon: house-fill
        href: index.qmd
        text: " "
      - href: about.qmd
        text: "Unit information"
      - href: 02-assessments/index.qmd
        text: "Assessments"
      - href: schedule.qmd
        text: "Schedule"
      - href: cheatsheets.qmd
        text: "Cheatsheets"
    right:
      - href: 04-help/index.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto