project:
  type: website

website:
  title: "BIOL2022"
  page-footer: "Unless otherwise indicated, the content of this handbook (whether on Canvas, or on GitHub) is licensed under a [CC-BY 4.0 License](https://creativecommons.org/licenses/by/4.0/). The images on this page are licensed through Adobe Stock and are protected by Adobe's copyright. These images may **not** be reproduced, distributed, or used without proper licensing from Adobe." 
  navbar:
    left:
      - icon: house-fill
        href: index.qmd
        text: " "
      - href: about.qmd
        text: "Unit information"
      - href: 02-assessments/index.qmd
        text: "Assessments"
      - href: schedule.qmd
        text: "Schedule"
      - href: cheatsheets.qmd
        text: "Cheatsheets"
    right:
      - href: 04-help/index.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf: 
    toc: true
  

execute:
  freeze: auto