project:
  type: website

website:
  title: "BIOL2022"
  search: true
  drafts: []
    # - module01/103-week02.qmd
    # - module01/104-week03.qmd
    # - module02/202-timeline.qmd
    # - module02/203-projects.qmd
    # - module02/204-report1.qmd
    # - module02/205-resources.qmd
    # - module03/302-week09.qmd
    # - module03/303-week10.qmd
    #- module03/304-week11.qmd
  draft-mode: visible # unlinked
  navbar:
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - icon: mortarboard-fill
        href: https://canvas.sydney.edu.au/courses/67437
        text: "Canvas"
      - icon: info-circle-fill
        text: "Unit Information"
        href: unit-information.qmd
      - icon: clipboard-check
        text: "Assessments"
        href: assessments/assessments.qmd
      # - icon: calendar-event
      #   href: schedule.qmd
      #   text: "Schedule"
      - icon: file-earmark-text
        href: cheatsheets.qmd
        text: "Cheatsheets"
    right:
      - href: help.qmd
        text: Contact
  sidebar:
    title: "BIOL2022"
    style: floating
    contents:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: mortarboard-fill
        text: Canvas
        href: https://canvas.sydney.edu.au/courses/74353/
      - icon: chat-dots-fill
        text: Ed
        href: https://edstem.org/au/courses/36475/
      - icon: calendar-week
        text: Schedule and weekly content
        href: schedule.qmd
      - icon: clipboard-check
        text: Assessments
        href: assessments/assessments.qmd
      - icon: info-circle-fill
        text: Unit information
        href: unit-information.qmd
      - icon: envelope-fill
        text: Contact
        href: help.qmd
      - icon: file-earmark-text
        text: Cheatsheets
        href: cheatsheets.qmd


format:
  html:
    theme: simplex # cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united
    fontsize: 15px
    grid:
      sidebar-width: 300px
    css: assets/timeline.css
    toc: true
    navbar: false
    sidebar: true
    # page-layout: full
    

editor:
  render-on-save: true

execute:
  freeze: auto
