project:
  type: website

website:
  title: "BIOL2022"
  navbar:
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - icon: info-circle-fill
        text: "Unit Information"
        href: unit-information.qmd
      - icon: clipboard-check
        text: "Assessments"
        href: assessments/assessments.qmd
      # - icon: calendar-event
      #   href: schedule.qmd
      #   text: "Schedule"
      - icon: file-earmark-text
        href: cheatsheets.qmd
        text: "Cheatsheets"
    right:
      - href: 04-help/index.qmd
        text: Contact
  sidebar: 
    style: floating
    collapse-level: 1
    contents:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: question-circle-fill
        text: "<b>Am I ready for BEDA?</b>"
        href: prerequisites.qmd
      - icon: info-circle-fill
        text: "Unit Information"
        href: unit-information.qmd
      # - icon: calendar-event
      #   text: Schedule
      #   href: schedule.qmd
      - icon: file-earmark-text
        text: Cheatsheets
        href: cheatsheets.qmd
      - icon: envelope-fill
        text: Contact us
        href: help.qmd
      - text: ---
      # - icon: easel3-fill
      #   text: Lectures
      #   href: lectures.qmd
      - icon: clipboard-check
        text: Assessments (info)
        href: assessments/assessments.qmd
      - text: ---
      - icon: book
        text: "<b>Practicals</b>"
      - section: "🐝 Module 1 (Wk 01-03)"
        contents:
          - href: module01/101-intro.qmd
            text: "**Please read first**"
          - module01/102-week01.qmd
          - module01/103-week02.qmd
          - href: module01/105-images.qmd
            text: "&nbsp; &nbsp; &nbsp; &nbsp; Intertidal site images"
          - href: module01/106-species-id.qmd
            text: "&nbsp; &nbsp; &nbsp; &nbsp; Species ID guide"
          - module01/104-week03.qmd
      - section: "🐝 Module 2 (Wk 04-08)"
        contents:
          - href: module02/201-intro.qmd
            text: "**Please read first**"
          - module02/202-timeline.qmd
          - module02/203-projects.qmd
          - module02/204-report1.qmd
          - module02/205-resources.qmd
      - section: "🐝 Module 3 (Wk 09-12)"
        contents:
          - href: module03/301-intro.qmd
            text: "**Please read first**"
          - module03/302-week09.qmd
          - module03/303-week10.qmd
          - module03/304-week11.qmd
          - module03/305-week12.qmd


format:
  html:
    theme: simplex # cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united
    fontsize: 15px
    grid:
      sidebar-width: 300px
    css: assets/timeline.css
    toc: true
    navbar: false
    sidebar: true
    # page-layout: full
    draft-mode: visible # unlinked

editor:
  render-on-save: true

execute:
  freeze: auto