project:
  type: website
  render:
    - "**/*.qmd"
    - "!_book/**"
    - "!schedule.qmd"

website:
  title: "BIOL2022"
  search: true
  navbar:
    left:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: clipboard-check
        text: Assessments
        href: assessments/assessments.qmd
      - icon: info-circle-fill
        text: Unit information
        href: unit-information.qmd
      - icon: envelope-fill
        text: Contact
        href: help.qmd
      - icon: file-earmark-text
        text: Cheatsheets
        href: cheatsheets.qmd
    right:
      - icon: mortarboard-fill
        text: Canvas
        href: https://canvas.sydney.edu.au/courses/74353/
      - icon: chat-dots-fill
        text: Ed
        href: https://edstem.org/au/courses/36475/

filters:
  - filters/learning-path.lua

format:
  html:
    theme: simplex
    fontsize: 15px
    css:
      - assets/timeline.css
      - assets/manual-headings.css
    toc: true

editor:
  render-on-save: true

execute:
  freeze: auto
