project:
  type: website
  render:
    - "**/*.qmd"
    - "!_book/**"

website:
  title: "BIOL2022"
  search: true
  sidebar:
    title: "BIOL2022"
    style: floating
    contents:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: mortarboard-fill
        text: Canvas
        href: https://canvas.sydney.edu.au/courses/74353/
      - icon: chat-dots-fill
        text: Ed
        href: https://edstem.org/au/courses/36475/
      - icon: calendar-week
        text: Schedule and weekly content
        href: schedule.qmd
      - icon: clipboard-check
        text: Assessments
        href: assessments/assessments.qmd
      - icon: info-circle-fill
        text: Unit information
        href: unit-information.qmd
      - icon: envelope-fill
        text: Contact
        href: help.qmd
      - icon: file-earmark-text
        text: Cheatsheets
        href: cheatsheets.qmd


format:
  html:
    theme: simplex
    fontsize: 15px
    grid:
      sidebar-width: 300px
    css: assets/timeline.css
    toc: true

editor:
  render-on-save: true

execute:
  freeze: auto
