project:
  type: website

website:
  title: "BIOL2022"
  navbar:
    left:
      - icon: house-fill
        href: index.qmd
        text: "Home"
      - icon: info-circle-fill
        text: "Unit Information"
        href: unit-information.qmd
      - icon: clipboard-check
        text: "Assessments"
        href: assessments/assessments.qmd
      - icon: calendar-event
        href: schedule.qmd
        text: "Schedule"
      - icon: file-earmark-text
        href: cheatsheets.qmd
        text: "Cheatsheets"
    right:
      - href: 04-help/index.qmd
        text: Contact
  sidebar: 
    style: floating
    contents:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: info-circle-fill
        text: "Unit Information"
        href: unit-information.qmd
      - icon: clipboard-check
        text: Assessments
        href: assessments/assessments.qmd
      - icon: calendar-event
        text: Schedule
        href: schedule.qmd
      - icon: file-earmark-text
        text: Cheatsheets
        href: cheatsheets.qmd
      - icon: envelope-fill
        text: Contact us
      - text: ---
      - icon: book
        text: "Practicals"
      - section: "Module 1"
        contents:
          - module01/101-intro.qmd
          - module01/102-week01.qmd
          - module01/103-week02.qmd
          - module01/104-week03.qmd
      - text: ---
      - text: Send us feedback

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: false
    navbar: false
    sidebar: true
    # page-layout: full
    
  
editor:
  render-on-save: true

execute:
  freeze: auto