---
title: "Preface"
editor:
  render-on-save: true
---

**Welcom to BEDA.** This unit is designed to help you understand the principles of experimental design and data analysis in biology. Unlike most other statistical units, BEDA focuses on the **practical** aspects of data analysis. We assume that you already have a basic understanding of statistical concepts, and we build on that knowledge, focusing on the **how** and **why** of statistical methods:

- *How* do we design a good study?
- *Why* does study design make a difference in the results we get?
- *Why* is it important to understand the context in which we use statistical tests?

Importantly, **attending labs is crucial to your learning** as most of the data we use are collected by you – please do not skip any of them!

## How to use this handbook

This handbook has been designed to be used in conjunction with the lectures and practicals. It contains all the information you need to complete the unit, including:

- **Lecture notes**: These are available in the [content section](content.qmd) and provide a summary of the key concepts covered in each lecture.
- **Practical activities**: These are available in the [schedule section](03-resources/schedule.qmd) and provide a hands-on approach to learning the concepts covered in the lectures.
- **Assessments**: These are available in the [assessments section](02-assessments/index.qmd) and provide an opportunity to apply the concepts learned in the lectures and practicals.
- **Help and support**: If you have any questions or need help, please refer to the [help section](04-help/index.qmd) for resources and contact information.


