---
title: "Contact, Help & Support"
---

You can, at any time, contact Januar via email. Check the [Canvas](https://canvas.sydney.edu.au/courses/67437) site for his contact details.

## Consultation

BEDA has a dedicated consultation hour at least once every week, where you can ask questions about the unit, your projects, or any other related topics. All drop-in sessions are run by **Januar**. This is conducted via Zoom and the link is available on Canvas. Please check Ed for the full schedule of drop-in sessions.

### What is a drop-in session?

It is an informal meeting, where nothing is recorded and the general atmosphere is relaxed. There are no expectations for you to prepare anything in advance. Januar can help you with any questions you have about BEDA. You can also use this time to discuss your progress, ask for feedback, or seek advice on specific challenges you are facing.

## Ways to get more help
### Practicals
There is no better avenue for getting help than attending the practicals. Your demonstrators are more than happy to help you with any questions you have. Demonstrators can discuss your work with you, help you troubleshoot problems, and provide feedback on your projects. They are also academics and students themselves, so don't hesitate to ask them about their own research or experiences in their disciplines!

### Ed discussions
In many cases, Ed is the best place to ask for help. Posts on Ed are visible to all students, so you can benefit from the answers to questions that others have asked. Staff also monitor Ed regularly and you can expect responses within 24 hours on weekdays.

### Email
If you have a specific question that you would like to ask via email, please do so.
**Make sure to include the unit code (BIOL2022) in the subject line**, e.g. *"BIOL2022: Question about Assignment 1"*, so that Januar can easily identify your email (he teaches many units related to statistics).

## Feedback

If you need more feedback on your work, you can ask for it during the drop-in sessions. Januar will happily discuss your work in more detail. Many students find it helpful to bring their work to the drop-in sessions, so they can get specific feedback on their projects or assignments. This can be done before the submission deadline or after you have received your marks and feedback.

