In Module 1, you have learnt the principles for converting a biological observation or question of interest into practice. Here, you will build on this skill. You will sign up to a research project and go through the process of converting a biological idea into a research experiment, which you and your group will then do from start to finish, to answer it.

Two important things to note:

- **Read the Lab Manual before each practical (check the timeline)**
- **Come/listen to each lecture on the day we give them, or before your practical**

You will need to use the lecture information immediately in these pracs. You will use your knowledge and experience to design your project, collect the data, and analyse and interpret it appropriately.


## What you need to submit for this practical component

This assessment requires two separate submissions in Canvas:

1. **Report 1 group data [0%]**: The Excel file (spreadsheets) containing your Group’s data. This needs to be submitted by one group member on behalf of your group. **We will not mark your submission if the data is not provided.**
2. **Report 1 [25%]**: Your Individual Report on your experiment, in the format of a short scientific article.

## How you will get feedback

- You will receive informative, but not exhaustive, feedback on your report in relation to the marking matrix. This will show what you achieved against each criterion, and why.
- To help you understand how you could improve, it helps enormously if you make a conscious effort to compare your submitted work against others. To facilitate this, I will post the best report written for your particular project.
- Should you want feedback beyond this, please reflect on your report and write a summary of how your report compares to the best one, addressing each of the marking criteria. Once you’ve done that, please email me to request an appointment, attaching your summary to the email message. BUT please note that because of the large class size, I may not be able to meet with everyone who wants to. As I am sure you will appreciate, I will give priority to any students with low/fail marks.


::::: {.content-visible unless-format="docx"}
\includepdf[pages=1-3, landscape=false]{assets/timeline_v3.pdf}
:::::
