---
title: '<i class="bi bi-flask me-2" aria-hidden="true"></i> **Week 11**: Multivariate methods in biology (continued)'
number-sections: false
toc-location: left
---

::: {.border .rounded .p-3 .mb-4 .bg-body-tertiary}
**Module 3 objectives**

This module introduces widely used techniques for analysing multivariate biological data. By the end of this module, you will be able to:

- Understand the principles underlying **Principal Components Analysis (PCA)** and **Non-metric Multidimensional Scaling (nMDS)**
- Be familiar with the concepts behind **multivariate hypothesis testing** using **permutational techniques** such as **ANOSIM** and **PERMANOVA**
- Be able to **plan and conduct experiments** that test multivariate hypotheses
- Know how to **carry out these analyses using relevant statistical software**
- Be able to **interpret, present, and report** your findings clearly and effectively

:::

For this specific practical you will:
- Analyse and interpret your group data using multivariate techniques learnt in weeks 1 (PCA) and 2 (nMDS, PERMANOVA, SIMPER (if appropriate, etc). 
- Perform analyses (ANOVA, regressions etc) to test additional univariate hypotheses.



## Outline

At the end of the practical you should have:

1. Appropriate outputs for your community structure analyses
   - nMDS (saved as suitable image file)
   - PERMANOVA results (in rtf/doc file)
   - SIMPER if justified
2. Appropriate outputs for your PCA
   - File with Jamovi or R output
3. Univariate tests using your PCA results
   - File with Jamovi or R output with Regression and/or ANOVA results (testing hypotheses using your newly derived PCs)

## Your own data
At this stage it’s very easy to fiddle with your data – is there any reason you might want to standardise or transform your data in any way? Some things to consider at this stage:

- Do the abundances matter?
- Are you intending to make every sample equal?
- Would it be worth analysing using your data at a higher “taxonomic” level?



If you don’t complete your analyses, I will make the program available to you outside of prac times. There will also be further support in Week 13 for any remaining analyses.
