---
title: '<i class="bi bi-flask me-2" aria-hidden="true"></i> **Weeks 12 and 13**: Multivariate methods in biology (continued)'
number-sections: false
toc-location: left
---

::: {.border .rounded .p-3 .mb-4 .bg-body-tertiary}
**Module 3 objectives**

This module introduces widely used techniques for analysing multivariate biological data. By the end of this module, you will be able to:

- Understand the principles underlying **Principal Components Analysis (PCA)** and **Non-metric Multidimensional Scaling (nMDS)**
- Be familiar with the concepts behind **multivariate hypothesis testing** using **permutational techniques** such as **ANOSIM** and **PERMANOVA**
- Be able to **plan and conduct experiments** that test multivariate hypotheses
- Know how to **carry out these analyses using relevant statistical software**
- Be able to **interpret, present, and report** your findings clearly and effectively

:::


## Outline

- **Week 12:** Carry out additional analyses, summarise your findings, and review guidance on describing multivariate methods and results in your report. Demonstrators will provide support with this work.
- **Week 13:** Further support for additional analyses and any remaining work.

During these weeks, we will be in the lab to help with any analyses that groups wish to undertake. This may involve integrating the analyses (e.g. testing the relationships between PCs and univariate measures) or tweaking (not twerking) your analyses by examining subsets of your data using the options available in Jamovi.

## Marking scheme

The marking scheme is included in the Week 9 practical notes and is also available on Canvas, in the Assignments section under **Report 2**.
