---
title: "Interactive Timeline"
format: html
---

<style>
.callout-note {
  padding: 1em;
  border: 1px solid #ccc;
  border-left: 5px solid #f0ad4e;
  margin: 1em 0;
  background-color: #fcf8e3;
}
.callout-important {
  padding: 1em;
  border: 1px solid #ccc;
  border-left: 5px solid #d9534f;
  margin: 1em 0;
  background-color: #f2dede;
}
h4 {
  margin-top: 1em;
  margin-bottom: 0.5em;
}
ul {
  margin-top: 0.5em;
}
</style>

<div id="root"></div>

<script src="https://unpkg.com/react@17/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
<script src="https://unpkg.com/react-chrono@1.22.0/dist/react-chrono.min.js"></script>
<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

<script type="text/babel">
  const { Chrono } = window.ReactChrono;

  const items = [
  {
    title: "Weeks 2-3",
    cardTitle: "Project Signup",
    cardDetailedText: (
      <div>
        <p><em>Before</em> Module 2 begins, sign up to a project group for Module 2 in your practical session.</p>
        <ul>
          <li>View available projects <a href="203-projects.qmd">here</a>.</li>
          <li>Once you have picked a project of interest, sign up to a group in your practical session on Canvas.</li>
          <li>Every person in your group should be in the same practical session.</li>
        </ul>
      </div>
    )
  },
  {
    title: "Week 4",
    cardTitle: "Project Planning and Pilot Study",
    cardDetailedText: (
      <div>
        <h4>In your practical session</h4>
        <ul>
          <li>Discuss and plan your project with your group.</li>
          <li>Pick up any gear you need to run your pilot study.</li>
        </ul>
        <h4>In your own time</h4>
        <ul>
          <li>After the practical in Week 4, contribute to your group’s pilot study work.</li>
          <li>Read relevant literature.</li>
          <li>Start preparing for your written report.</li>
        </ul>
        <h4>Details</h4>
        <ul>
          <li><strong>Form your hypothesis</strong>: as a group, convert the general biological question into specific biological hypotheses and predictions.</li>
          <li><strong>Plan the design of your main experiment</strong>: with your group, design a simple experiment to test the hypothesis. Ensure your design can be analysed using the stats you are familiar with (e.g. from Januar’s and Clare’s lectures, and Module 1 practicals). Draw a graph of how you expect your data to look (refer to Clare’s lectures). Decide what stats analysis is appropriate and why (refer to Clare’s lectures). If you can’t work this out, you are not ready to run your experiment.</li>
          <li><strong>Draft your data sheets</strong>: as a group, draft your data sheets for data collection (you may need to modify after your pilot study). This will ensure you collect all the data you should and collect it all in the same way.</li>
          <li><strong>Work out what equipment you’ll need</strong>: decide equipment you need to do the research based around what we can supply you. Consult Clare, technical staff and/or demonstrators then make a list.
            <ul>
              <li>For some projects, you will be able to take gear home straight away to run a pilot study.</li>
              <li>For others, you need to plan now and pick up gear in consultation with the technical staff. When contacting the tech staff, ensure you state your <strong>name</strong> and <strong>day</strong>, <strong>group number</strong> and <strong>project</strong>, e.g. BIOL2022 WED 2 to 4pm, Group 7 birds, Joe Blogs.</li>
            </ul>
          </li>
          <li>Plan your pilot study in class and run it before Week 5 practical session: this will help you refine your main experiment. Everyone in your group must contribute.</li>
        </ul>
        <div className="callout-note">
          <p>Clare, technical staff and demonstrators will be available in the Lab to discuss expectations for this practical module and plans for the coming weeks in session, and in your own time. Your group should aim to be self-sufficient out of practical times. However, for technical help outside practicals, or last-minute changes gear to be picked up, please contact heather.sowden@sydney.edu.au.</p>
        </div>
      </div>
    )
  },
  {
    title: "Week 5",
    cardTitle: "Finalise Experiment Design",
    cardDetailedText: (
      <div>
        <h4>In your practical session</h4>
        <ul>
          <li>Finalise the design and plans for your main experiment based on your pilot study and your reading of the relevant scientific literature</li>
          <li>Pick up any gear that you need for your main experiment.</li>
        </ul>
        <h4>Details</h4>
        <ul>
          <li>Discuss what you learnt from your pilot study with your group.</li>
          <li>Tweak the design of your main experiment if you need to: make any adjustments to your plans and finalise your main experiment and its experimental design.</li>
          <li>Know what stat tests you’ll be doing: ensure you know how you expect to statistically analyse your results, e.g. what your response and explanatory variable(s) are, what form and hence what stats test you intend to do.</li>
        </ul>
        <div className="callout-note">
          <p>Clare, technical staff and demonstrators will be available in the Lab to discuss your plans and provide feedback and gear. For technical help outside practicals, or last-minute changes gear to be picked up, please contact heather.sowden@sydney.edu.au.</p>
        </div>
      </div>
    )
  },
  {
    title: "Weeks 5-7",
    cardTitle: "Data Collection",
    cardDetailedText: (
      <div>
        <div className="callout-important">
          <p>There is no formal practical session in Week 6.</p>
        </div>
        <h4>In your own time</h4>
        <p>Set up your main experiment, run it, collect and collate the data. Everyone in your group must contribute.</p>
        <h4>Details</h4>
        <ul>
          <li>Collate the data: collate your group’s data into one Excel file – e.g. using Google Sheets. Include both a metadata worksheet and a clean results array in its own worksheet for data analysis. You can also have other worksheets for anything you want to record, plot, etc.</li>
          <li>Finalise data collation before week 7 practical if you can, leaving you more time for data analysis in Week 7 practical.</li>
        </ul>
        <div className="callout-note">
          <p>For technical help outside practicals, or last-minute changes gear to be picked up, please contact heather.sowden@sydney.edu.au.</p>
        </div>
      </div>
    )
  },
  {
    title: "Week 7",
    cardTitle: "Data Analysis",
    cardDetailedText: (
      <div>
        <h4>In your practical session</h4>
        <ul>
          <li>Finalise data collation of your main experiment (including metadata).</li>
          <li>Start data analysis of your main experiment (and if possible, complete it).</li>
          <li>Decide what plots and particular stats output you will need to report in the results section of your written report.</li>
        </ul>
        <h4>Details</h4>
        <ul>
          <li><strong>If you have not done so already, finalise data collation</strong>: spend no more than 30 mins of the practical finalising data collation into an Excel spreadsheet. Preferably, have this done before this practical session.</li>
          <li>Metadata: include a metadata worksheet that summarises important information referring to your data, such as:
            <ul>
              <li>names of group members</li>
              <li>the dates the experiment was run</li>
              <li>sites where you collected data</li>
              <li>response (i.e. dependent) variables and their units of measurement,</li>
              <li>explanatory (i.e. independent) variables, such as treatments (and the levels within each treatment) and any continuous variables</li>
              <li>anything to help you understand your project and data if you were to publish it for the world to see and understand, e.g. what the columns in your data sheet mean</li>
            </ul>
          </li>
          <li><strong>Plot, analyse and interpret</strong>: in the remaining practical time (at least an hour) using your group’s data set, each group member should individually learn to use Excel and R or SPSS to plot your data, run appropriate statistical analyses and interpret your results. You need to think about what stats results you need in the results section of your written report. Fantastic if you can complete this task by the end of week 7.</li>
        </ul>
        <div className="callout-note">
          <p>It is okay to work with other group members to plot and run the tests. However, each group member should do the analyses on their own so that they learn; watching someone else is not enough.</p>
        </div>
      </div>
    )
  },
  {
    title: "Weeks 7-8",
    cardTitle: "Report Drafting",
    cardDetailedText: (
      <div>
        <h4>In your own time</h4>
        <ul>
          <li>Continue your data analysis if you have yet to complete it.</li>
          <li>Start drafting your report.</li>
        </ul>
        <h4>Details</h4>
        <ul>
          <li>Data analysis: as above.</li>
          <li>Drafting your report: make a start on your report, e.g. framework for Introduction, Materials and Methods, and Results. You could leave the Discussion until you have finalised your Results. Refer to:
            <ul>
              <li>Clare’s tips on writing your report</li>
              <li>More tips on writing your report</li>
              <li>Module 2: Marking scheme for Report 1</li>
            </ul>
          </li>
        </ul>
      </div>
    )
  },
  {
    title: "Week 8",
    cardTitle: "Finalise Analysis and Report",
    cardDetailedText: (
      <div>
        <h4>In your practical session</h4>
        <ul>
          <li>Clare will go through writing your report.</li>
          <li>Finalise analyses, stats output and graphs.</li>
        </ul>
        <h4>Details</h4>
        <ul>
          <li>As a group: prepare your Excel data file for submission. The filename should be of the form Day-Time-Project, e.g. “WED2-4pmProj4A”. This file must include:
            <ul>
              <li>a metadata worksheet;</li>
              <li>a worksheet of the data array you will have imported to a stats package for analysis; and</li>
              <li>any other worksheets with workings, plots, etc.</li>
            </ul>
          </li>
          <li>As individuals: each group member needs to work on writing their report by:
            <ul>
              <li>completing their own results and graphs;</li>
              <li>deciding what they will include in their individual report; and</li>
              <li>deciding how they will present the data and the associated statistics.</li>
            </ul>
          </li>
        </ul>
      </div>
    )
  },
  {
    title: "Week 9",
    cardTitle: "Submission",
    cardDetailedText: (
      <div>
        <h4>Submission</h4>
        <p>Submit your group’s data and your written report in separate assignments in Canvas.</p>
        <h4>Details</h4>
        <ul>
          <li>There are two Canvas assignments for this assessment:
            <ul>
              <li>Report 1 Group Data: one person from your group needs to submit the group’s data for this Canvas assignment.</li>
              <li>Report 1 (individual): each person in your group needs to submit their own report for this Canvas assignment.</li>
            </ul>
          </li>
        </ul>
      </div>
    )
  }
];

  const App = () => (
    <div style={{ width: "100%", height: "100%" }}>
      <Chrono
        items={items}
        mode="VERTICAL_ALTERNATING"
        cardHeight={400}
        scrollable={{scrollbar: true}}
      />
    </div>
  );

  ReactDOM.render(<App />, document.getElementById('root'));
</script>