---
title: "Module 2 Timeline"
format:
  typst:
    toc: false
    number-sections: false
---

### Weeks 2--3 (before Module 2){#wk2}

**Summary:** You will need to **sign up** to a project group on Canvas. All groups will be formed by the end of Week 3, so you can start working on your project in Week 4.

#### In your practical session
Join a group on Canvas.

**All members of your group must be in the same practical session.**
Groups will be released in your practical session. You will need to go to Canvas site for BIOL2022, select "**People**" in the sidebar and click on the "**Report 1 Research Groups**" tab. There, you will see project groups which you can "enrol" in. Make sure to check the [Projects](203-projects.qmd) page for more information about each research project.

### Week 4 -- Module 2 begins in the Lab {#wk4}


**Summary:** Work with your group to discuss and plan your project. Pick up any gear that you need, to run your pilot study.

#### In your practical session
Discuss and plan your project with your group. You will also be introduced to the pilot study—a small-scale version of your main experiment that you will run this week (or next). Pick up any gear you need to run your pilot study.

**Details**:

- **Form your hypothesis:** As a group, convert the general biological question into specific hypotheses and predictions.
- **Plan the design of your main experiment:** With your group, design a simple experiment to test your hypothesis. Ensure your design can be analysed using the statistical methods you are familiar with (e.g., from Januar’s and Clare’s lectures, and Module 1 practicals). Draw a graph of how you expect your data to look (refer to Clare’s lectures). Decide what statistical analysis is appropriate and why. If you can’t work this out, you are not ready to run your experiment.
- **Draft your data sheets:** As a group, draft your data sheets for data collection (you may need to modify these after your pilot study). This will ensure you collect all the necessary data, and do so consistently.
- **Work out what equipment you’ll need:** Decide what equipment you need for your research, based on what we can supply. Consult Clare, technical staff, and/or demonstrators, then make a list. For some projects, you will be able to take gear home straight away to run a pilot study. For others, you need to plan now and pick up gear in consultation with the technical staff. When contacting technical staff, ensure you state your name, day, group number, and project (e.g., BIOL2022 WED 2–4pm, Group 7 birds, Joe Blogs).
- **Plan and run your pilot study:** Plan your pilot study in class and run it before the Week 5 practical session. This will help you refine your main experiment. **Everyone in your group must contribute.**

#### In your own time

After the prac in Week 4, contribute to your group’s pilot study practical work, read relevant literature, and start preparing for your written report.


### Week 5 {#wk5}
**Summary:** Finalise the design and plans for your main experiment based on your pilot study and your reading of the relevant scientific literature. Pick up any gear you need for your main experiment.

#### In your practical session

- **Discuss** what you learned from your pilot study with your group.
- **Adjust the design of your main experiment if needed:** make any necessary changes to your plans, and finalise your experimental design.
- **Confirm your statistical analysis:** ensure you know how you will analyse your results, including identifying your response and explanatory variables, and selecting the appropriate statistical test.

#### In your own time

- Set up your main experiment, run it, collect and collate the data. **Everyone in your group must contribute.** 
- **Collate the data:** collate your group’s data into one Excel file – e.g. using Google Sheets. Include both a metadata worksheet and a clean results array in its own worksheet for data analysis. You can also have other worksheets for anything you want to record, plot, etc.
Finalise data collation before week 7 prac if you can, leaving you more time for data analysis in Week 7 prac.


### Week 6 {#wk6}

**There is no formal practical session in Week 6.**

#### In your own time
Set up your main experiment, run it, collect and collate the data. **Everyone in your group must contribute.**


### Week 7 {#wk7}

**Summary:** Finalise collation of your main experiment data (including metadata). Begin analysing your main experiment data; aim to complete this if possible. Decide which plots and statistical outputs you will include in the results section of your written report.

#### In your practical session

**If you have not already done so, finalise your data collation:**  
Spend no more than 30 minutes of the practical session organising your data into an Excel spreadsheet. Preferably, complete this before the session.

**Metadata:**  
Include a metadata worksheet summarising key information about your data, such as:

- Names of group members
- Dates the experiment was run
- Sites where data were collected
- Response (dependent) variables and their units of measurement
- Explanatory (independent) variables, such as treatments (and levels within each treatment) and any continuous variables
- Any other details to help interpret your project and data, e.g., explanations of column headings

**Plot, analyse, and interpret:**  
During the remaining practical time (at least one hour), use your group’s dataset to individually learn how to use Excel and R or SPSS to plot your data, run appropriate statistical analyses, and interpret your results. Consider which statistical results you will need for the results section of your written report. Ideally, complete this task by the end of Week 7.

*Note:* It is fine to work with other group members to plot and run analyses. However, each group member should perform the analyses themselves to learn; simply watching others is not sufficient.


#### In your own time

Set up your main experiment, run it, collect and collate the data. Analyse and plot the data (the practicals also give you time to do this) if you have yet to complete it. 

**Drafting your report:** make a start on your report, e.g. framework for Introduction, Materials and Methods, and Results. You could leave the Discussion until you have finalised your Results. Refer to the following resources:

- Clare’s tips on writing your report
- More tips on writing your report
- Module 2: Marking scheme for project report


### Week 8 {#wk8}

**Summary:** Clare will go through writing your report. Finalise analyses, stats output and graphs.

#### In your practical session

As a group: prepare your Excel data file for submission. The filename should be of the form Day-Time-Project, e.g. “WED2-4pmProj4A”. This file must include:

- a metadata worksheet
- a worksheet of the data array you will have imported to a stats package for analysis
- any other worksheets with workings, plots, etc. 

As individuals: each group member needs to work on writing their report by: 

- completing their own results and graphs
- deciding what they will include in their individual report.
- deciding how they will present the data and the associated statistics.

#### In your own time

- Continue your data analysis if you have yet to complete it.
- Continue drafting your report.


### Week 9 {#wk9}

**Summary:** Submit your group’s data and your written report in separate assignments in Canvas. **There is a mid-semester break period where you may, if you wish, continue working on your project.** However, Module 3 begins this week so you will not be able to work on your project in the practical sessions.



#### In your own time

##### Submission

There are two Canvas assignments for this assessment:

**Report 1 Group Data:** one person from your group needs to submit the group’s data for this Canvas assignment

**Report 1: individual practical written report:** each person in your group needs to submit their own report for this Canvas assignment.


